// <auto-generated />
namespace University.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addlocationtoroom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlocationtoroom));
        
        string IMigrationMetadata.Id
        {
            get { return "202402291228293_add-location-to-room"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
